"""The three files Novayagraph owns, and the block it writes in the client's.

    .novgraph/rules.md      how to work with the graph. Ships with the client.
    .novgraph/skills.md     what the server serves. From the live /v1/tools.
    .novgraph/blueprint.md  this repository: codebase name, origin, briefing.

Three files because three different clocks. The pointer block exists because
CLAUDE.md and AGENTS.md are the only files an agent opens unprompted, so they
get an address and we keep the rules in files we can regenerate.
"""
from __future__ import annotations

import re
from pathlib import Path

from . import __version__
from . import catalog, transport

DIR_NAME = ".novgraph"

START = "<!-- novgraph:start -->"
END = "<!-- novgraph:end -->"

# Non-greedy, so two blocks collapse to one rather than merging.
_BLOCK_RE = re.compile(
    re.escape(START) + ".*?" + re.escape(END), re.DOTALL)

# NO VERSION HERE. It churned: two teammates on different clients rewrote
# all three files on every install, in a directory meant to be committed.
# write_all already compares CONTENT, which is the only identity that matters.
GENERATED_HEADER = (
    "<!-- Generated by `novgraph install`. Hand edits are overwritten. -->"
)


def dir_for(root: Path) -> Path:
    return Path(root) / DIR_NAME


# -- the pointer block --------------------------------------------------------

def pointer_block(codebase: str = "") -> str:
    """What goes in CLAUDE.md / AGENTS.md. Six lines: an address, not rules.
    Every line here is one of the user's we are spending."""
    named = ("This repository is indexed as `" + codebase + "`.\n"
             if codebase else "")
    return (
        START + "\n"
        "## Novayagraph\n"
        "\n"
        "Architecture, recorded intent and blast radius for this repository come\n"
        "from Novayagraph, reached with the `novgraph` command. **Read "
        "`.novgraph/rules.md`\n"
        "before non-trivial work here** -- it governs when and how to use it, and\n"
        "`.novgraph/skills.md` lists what can be asked.\n"
        + named +
        "\n"
        "Managed by `novgraph install`. Edits between these markers are overwritten;\n"
        "put your own instructions outside them.\n"
        + END
    )


def apply_pointer(path: Path, codebase: str = "") -> str:
    """Write the block in. Replaces between markers, never appends -- the old
    setup appended, and repos grew three contradictory sections."""
    block = pointer_block(codebase)
    if path.exists():
        original = path.read_text(encoding="utf-8")
    else:
        original = ""

    if _BLOCK_RE.search(original):
        updated = _BLOCK_RE.sub(lambda _m: block, original, count=1)
        # A second block can only exist if something went wrong before. Drop it.
        while len(_BLOCK_RE.findall(updated)) > 1:
            first = _BLOCK_RE.search(updated)
            rest = _BLOCK_RE.sub("", updated[first.end():], count=1)
            updated = updated[:first.end()] + rest
        state = "unchanged" if updated == original else "updated"
    elif original.strip():
        updated = original.rstrip("\n") + "\n\n" + block + "\n"
        state = "updated"
    else:
        updated = block + "\n"
        state = "created" if not path.exists() else "updated"

    if updated != original:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(updated, encoding="utf-8")
    return state


def remove_pointer(path: Path) -> bool:
    """Remove our block, leaving the user's text as it was."""
    if not path.exists():
        return False
    original = path.read_text(encoding="utf-8")
    if not _BLOCK_RE.search(original):
        return False
    stripped = _BLOCK_RE.sub("", original)
    stripped = re.sub(r"\n{3,}", "\n\n", stripped).strip()
    if not stripped:
        # The block was the whole file, so we are the ones who created it.
        # Leaving a 0-byte CLAUDE.md behind is litter that reads like the
        # user's own file; uninstall should leave no trace of what it made.
        try:
            path.unlink()
        except OSError:
            pass
        return True
    path.write_text(stripped + "\n", encoding="utf-8")
    return True


# -- .novgraph/rules.md ---------------------------------------------------------

RULES = """# Novayagraph rules

How this repository's agents use Novayagraph. Read before non-trivial work.

## What it is

A hosted knowledge graph over this codebase. It holds four things that cannot
be re-derived by reading files:

- **Structure** -- symbols, imports, calls, inheritance, plus inferred runtime
  relations no parser can see.
- **The why-feed** -- the recorded intent behind commits. Git stores what
  changed; this stores why, and what was traded away.
- **Co-change** -- files that historically change together with no static link.
  The highest-value edge in the graph, because it is invisible in the code.
- **Architecture** -- computed hubs, subsystems, layering, dependency cycles.

## When to call it

| Situation | Call |
| --- | --- |
| New to this codebase | `novgraph summary`, then `novgraph overview` |
| About to change a file | `novgraph why <path>` and `novgraph connections <path>` |
| Estimating blast radius | `novgraph impact <path>` |
| Chasing a regression | `novgraph recent` |
| Looking for something by meaning | `novgraph search "<query>"` |
| A decision-shaped question | `novgraph ask "<question>"` |
| After a meaningful commit | `novgraph record-why "<what and why>"` |

Skip all of it for trivial edits -- a typo fix does not need a blast radius.

## The rule that keeps it honest

**The graph is a cross-check, not an oracle.** It describes the indexed commit;
the working tree is the truth about what the code says right now. Read files
for current contents, and query the graph for the things files do not contain:
history, intent, coupling, consequence. When the two disagree, the working tree
wins on facts and the graph still wins on reasons.

## Write the why back

`novgraph record-why` after a commit that involved a real decision. That
write-back is what makes the memory compound -- a graph nobody writes to is a
snapshot, and the reasoning it holds is the only part no tool can recover
later.

## Credentials

The API key lives in this machine's credential store. `novgraph` loads it
itself; you never need to see, print, export or paste it. It is not in this
repository, and it must not be put here. If a call reports HTTP 401, the fix is
`novgraph install <NEW KEY>` with a key from https://app.trynovaya.com, not a
retry.

## When it does not answer

If the repository is not indexed, connect it at https://app.trynovaya.com and
wait for its job to finish. Do not index locally -- there is no local engine,
and no local graph for one to write to. Report a stale or missing graph rather
than working around it silently; `novgraph doctor` says which of those it is.
"""


def rules_md(cat: dict | None = None) -> str:
    """Method, preferred from the server.

    RULES below is a FALLBACK, not the source. Serving guidance means an
    improvement to how agents should use the graph reaches a client installed
    months ago -- the same argument as LAW 16, applied to prose. A client that
    shipped its own copy freezes our judgement at install time.
    """
    served = str((cat or {}).get("guidance") or "").strip()
    return GENERATED_HEADER + "\n\n" + (served or RULES)


# -- .novgraph/skills.md --------------------------------------------------------

def skills_md(cat: dict) -> str:
    """The tool catalog, written from what the server actually serves."""
    lines = [
        GENERATED_HEADER,
        "",
        "# Novayagraph tools",
        "",
        "Generated from `GET " + transport.base_url() + "/v1/tools`, so this list"
        " is what",
        "the server serves -- not a copy of it that can drift.",
        "",
        "Two ways to call each one, both already wired by `novgraph install`:",
        "",
        "- **Shell** -- `novgraph <verb> [args]`, in any repository.",
        "- **MCP** -- the same tools appear natively in clients that speak MCP.",
        "",
        "Add `--codebase <name>` to target a repository other than this one, and",
        "`--json` to any verb for the raw response.",
        "",
    ]
    for spec in (cat or {}).get("commands") or []:
        if not isinstance(spec, dict) or not spec.get("name"):
            continue
        name = str(spec["name"])
        lines += ["## The `/" + name + "` command", "",
                  "Typed in the agent's chat: `/" + name + " <workflow>`, or `$"
                  + name + " <workflow>` in Codex.", ""]
        if spec.get("argument_hint"):
            lines += ["Workflows: `" + " ".join(str(spec["argument_hint"]).split())
                      + "`", ""]
    for tool in catalog.normalise(cat):
        lines.append("## `novgraph " + tool.verb + "`")
        lines.append("")
        if tool.description:
            lines.append(tool.description.strip())
            lines.append("")
        if tool.properties:
            lines.append("| argument | required | meaning |")
            lines.append("| --- | --- | --- |")
            for arg in tool.properties:
                lines.append("| `" + arg + "` | "
                             + ("yes" if arg in tool.required else "no") + " | "
                             + tool.describe(arg).replace("|", "/") + " |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# -- .novgraph/blueprint.md -----------------------------------------------------

def blueprint_md(cat: dict, codebase: str, origin: str = "") -> str:
    """What `novgraph install` established here.

    A record of the SETUP, scoped to what the distribution did: which codebase
    this checkout is bound to, and what was wired. It carried the server's API
    briefing once -- 58 lines telling an agent to hand-roll a Bearer request,
    which contradicted rules.md and had nothing to do with this repository.
    The word "blueprint" already meant that briefing elsewhere in the product,
    and the name pulled the content in.
    """
    lines = [
        GENERATED_HEADER,
        "",
        "# Novayagraph setup for this repository",
        "",
        "| | |",
        "| --- | --- |",
        "| Codebase name | `" + (codebase or "UNRESOLVED") + "` |",
    ]
    if origin:
        lines.append("| Origin | " + origin + " |")
    lines.append("| API | " + transport.base_url() + " |")
    lines.append("")

    if codebase:
        lines += [
            "Pass this name explicitly on every call that takes `--codebase` when",
            "working across repositories. Within this checkout `novgraph` supplies it",
            "for you.",
            "",
        ]
    else:
        lines += [
            "**This repository is not indexed yet.** Connect it at",
            "https://app.trynovaya.com and wait for its job to reach done, then run",
            "`novgraph install` again to fill this in. Until then every graph call will",
            "report that there is nothing to read -- which is the correct answer, not",
            "a reason to fall back to grepping the tree and calling it context.",
            "",
        ]

    lines += ["Method is in `rules.md`; the tools are in `skills.md`. This file "
              "only", "records what setup bound here.", ""]
    return "\n".join(lines).rstrip() + "\n"


def write_all(root: Path, cat: dict, codebase: str, origin: str = ""):
    """Write the three files. Returns [(path, state)] for the install report."""
    target = dir_for(root)
    target.mkdir(parents=True, exist_ok=True)
    written = []
    for name, body in (("rules.md", rules_md(cat)),
                       ("skills.md", skills_md(cat)),
                       ("blueprint.md", blueprint_md(cat, codebase, origin))):
        path = target / name
        before = path.read_text(encoding="utf-8") if path.exists() else None
        if before == body:
            written.append((path, "unchanged"))
            continue
        path.write_text(body, encoding="utf-8")
        written.append((path, "created" if before is None else "updated"))
    return written
